model_params:
  name: "default_model"
  version: "1.0"
  type: "classification"

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"

preprocessing:
  scaling: "standard"
  categorical_encoding: "label"
  missing_values: "mean"

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  test_size: 0.2
  random_state: 42
