version: '3.8'

services:
  jarvis:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      - ../:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:password@db:5432/jarvis
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jarvis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
