environment: production
debug: false
data_path: "/data/production/"
model_path: "/models/production/"
logging:
  level: INFO
  file: "logs/prod.log"
database:
  host: prod-db.example.com
  port: 5432
  name: ml_prod_db
