# Basic config for JARVIS
ui:
  enabled: true
logging:
  level: INFO
llm:
  model:
    name: distilgpt2  # Base model to use
    type: transformer
    max_length: 2048  # Increased context length
    temperature: 0.7
    low_cpu_mem_usage: true
    device_map: auto
  auto_load: true
  memory_management:
    cache_size: 1000
database:
  type: sqlite
  path: "db/knowledge.db"
jarvis_model:
  name: "JARVIS"
