models:
  conversation:
    type: "transformer"
    vocab_size: 40000
    embedding_size: 768
    num_heads: 8
    num_layers: 6
    dropout: 0.1

  sentiment:
    type: "classifier"
    vocab_size: 40000 
    embedding_size: 512
    num_classes: 3  # positief, neutraal, negatief

training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 10
  validation_split: 0.2

data:
  train_dir: "data/dutch/training"
  valid_dir: "data/dutch/validation"
  vocab_file: "data/dutch/vocab.txt"
