model:
  type: "spacy"
  name: "nl_core_news_sm"  # Using smaller model by default for faster loading
  max_length: 100

optimization:
  device: "auto"
  batch_size: 1

generation:
  max_new_tokens: 50
  no_repeat_ngram_size: 3
  temperature: 0.7
  top_p: 0.9

spacy:
  # Additional SpaCy-specific settings
  pipeline: ["tagger", "parser", "ner"]
  disable: []
